//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenPractico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zona
    {
        public Zona()
        {
            this.PuntosInteres = new HashSet<PuntosInteres>();
            this.PuntosInteres1 = new HashSet<PuntosInteres>();
        }
    
        public int IdZona { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<PuntosInteres> PuntosInteres { get; set; }
        public virtual ICollection<PuntosInteres> PuntosInteres1 { get; set; }
    }
}
